"""add feature flags

Revision ID: 21b7d9a76c9d
Revises: e54a6de25b64
Create Date: 2026-03-05 08:30:31.676466

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21b7d9a76c9d"
down_revision: str | None = "e54a6de25b64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flags",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("audience", sa.String(length=50), server_default="disabled", nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "feature_flag_users",
        sa.Column("flag_key", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flag_key"],
            ["feature_flags.key"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("flag_key", "user_id"),
    )
    # ### end Alembic commands ###

    # Seed initial feature flag
    op.execute("INSERT INTO feature_flags (key, audience) VALUES ('watercolor_theme', 'disabled')")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feature_flag_users")
    op.drop_table("feature_flags")
    # ### end Alembic commands ###
