"""add trees persons relationships events tables

Revision ID: 289ffbef301e
Revises: 7155daa426c5
Create Date: 2026-02-09 14:06:40.659817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289ffbef301e'
down_revision: Union[str, None] = '7155daa426c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trees_user_id'), 'trees', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_tree_id'), 'events', ['tree_id'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_tree_id'), 'persons', ['tree_id'], unique=False)
    op.create_table('event_persons',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'person_id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tree_id', sa.Uuid(), nullable=False),
    sa.Column('source_person_id', sa.Uuid(), nullable=False),
    sa.Column('target_person_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_source_person_id'), 'relationships', ['source_person_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_person_id'), 'relationships', ['target_person_id'], unique=False)
    op.create_index(op.f('ix_relationships_tree_id'), 'relationships', ['tree_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_tree_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_target_person_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_person_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_table('event_persons')
    op.drop_index(op.f('ix_persons_tree_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_events_tree_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_trees_user_id'), table_name='trees')
    op.drop_table('trees')
    # ### end Alembic commands ###
