"""add faq_entries

Revision ID: 34cd55d04bad
Revises: 3f7d5f997c37
Create Date: 2026-06-06 17:25:19.143015

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34cd55d04bad"
down_revision: str | None = "3f7d5f997c37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faq_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_en", sa.Text(), nullable=False),
        sa.Column("answer_en", sa.Text(), nullable=False),
        sa.Column("question_nl", sa.Text(), nullable=False),
        sa.Column("answer_nl", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("published", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # Seed the published FAQ with the content that previously lived in the
    # frontend i18n files, so the landing page has content from day one.
    faq_table = sa.table(
        "faq_entries",
        sa.column("id", sa.Uuid()),
        sa.column("question_en", sa.Text()),
        sa.column("answer_en", sa.Text()),
        sa.column("question_nl", sa.Text()),
        sa.column("answer_nl", sa.Text()),
        sa.column("sort_order", sa.Integer()),
        sa.column("published", sa.Boolean()),
    )
    seed = [
        {
            "question_en": "Is this therapy?",
            "answer_en": (
                "No. Traumatrees is a tool for personal reflection. It is not therapy, "
                "counselling, or crisis support. If you are in crisis, please reach out to a "
                "professional or a local helpline."
            ),
            "question_nl": "Is dit therapie?",
            "answer_nl": (
                "Nee. Traumabomen is een instrument voor persoonlijke reflectie. Het is geen "
                "therapie, hulpverlening of crisishulp. Als je in crisis bent, neem dan contact "
                "op met een professional of een hulplijn bij jou in de buurt."
            ),
        },
        {
            "question_en": "Can you read what I write?",
            "answer_en": (
                "No. Your entries are encrypted on your device before they reach our server, "
                "using Argon2id and AES-256-GCM. We store only unreadable ciphertext and have no "
                "way to decrypt it."
            ),
            "question_nl": "Kunnen jullie lezen wat ik schrijf?",
            "answer_nl": (
                "Nee. Je notities worden op je eigen apparaat versleuteld voordat ze onze server "
                "bereiken, met Argon2id en AES-256-GCM. We bewaren alleen onleesbare cijfertekst "
                "en kunnen die niet ontsleutelen."
            ),
        },
        {
            "question_en": "What if I lose my passphrase?",
            "answer_en": (
                "Then your data is gone, and no one, including us, can recover it. That is the "
                "cost of encryption only you can open. Keep your passphrase somewhere safe, and "
                "consider setting a hint."
            ),
            "question_nl": "Wat als ik mijn wachtwoord verlies?",
            "answer_nl": (
                "Dan zijn je gegevens weg, en niemand, ook wij niet, kan ze herstellen. Dat is de "
                "prijs van versleuteling die alleen jij kunt openen. Bewaar je wachtwoord op een "
                "veilige plek, en overweeg een hint in te stellen."
            ),
        },
        {
            "question_en": "Do I have to map everything at once?",
            "answer_en": (
                "No. You set the pace. Start with one person, leave the rest, and come back "
                "whenever you want."
            ),
            "question_nl": "Moet ik alles in een keer in kaart brengen?",
            "answer_nl": (
                "Nee. Jij bepaalt het tempo. Begin met een persoon, laat de rest, en kom terug "
                "wanneer je wilt."
            ),
        },
    ]
    op.bulk_insert(
        faq_table,
        [
            {**row, "id": uuid.uuid4(), "sort_order": i, "published": True}
            for i, row in enumerate(seed, start=1)
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("faq_entries")
    # ### end Alembic commands ###
