"""add turning points

Revision ID: 73326c37101f
Revises: db3cf53ce328
Create Date: 2026-02-21 21:00:27.532823

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73326c37101f"
down_revision: str | None = "db3cf53ce328"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "turning_points",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tree_id", sa.Uuid(), nullable=False),
        sa.Column("encrypted_data", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tree_id"], ["trees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_turning_points_tree_id"), "turning_points", ["tree_id"], unique=False)
    op.create_table(
        "turning_point_persons",
        sa.Column("turning_point_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["persons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["turning_point_id"], ["turning_points.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("turning_point_id", "person_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("turning_point_persons")
    op.drop_index(op.f("ix_turning_points_tree_id"), table_name="turning_points")
    op.drop_table("turning_points")
    # ### end Alembic commands ###
