"""add tree is_demo column

Revision ID: db3cf53ce328
Revises: 5e3dac0517ba
Create Date: 2026-02-19 16:46:19.626993

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db3cf53ce328"
down_revision: str | None = "5e3dac0517ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trees", sa.Column("is_demo", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trees", "is_demo")
    # ### end Alembic commands ###
