"""add last_active_at to users

Revision ID: e54a6de25b64
Revises: ffd7fc537608
Create Date: 2026-03-02 08:56:07.173936

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e54a6de25b64"
down_revision: str | None = "ffd7fc537608"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_active_at")
    # ### end Alembic commands ###
