"""add encrypted_key_ring to users

Revision ID: e9dcfe4e05d2
Revises: 2f8000e0372b
Create Date: 2026-02-24 10:05:13.113478

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9dcfe4e05d2"
down_revision: str | None = "2f8000e0372b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("encrypted_key_ring", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "encrypted_key_ring")
    # ### end Alembic commands ###
