#!/bin/sh
# Xcode Cloud custom build script. Runs after the repo is cloned and before
# dependency resolution / the archive build.
#
# A fresh clone has neither the Xcode project nor the core framework:
#   - mobile/ios/Traumatrees.xcodeproj is generated by xcodegen and gitignored.
#   - The KMP core is consumed as a Gradle-built XCFramework under
#     mobile/core/build/ (a build output, also not committed).
# This script rebuilds both so the subsequent archive finds a real project
# that links a real framework. Without it Xcode Cloud fails with
# "Project Traumatrees.xcodeproj does not exist".
#
# Location matters: Xcode Cloud only runs this when the folder is named exactly
# ci_scripts and sits next to the Xcode project it builds (mobile/ios), and the
# file is named ci_post_clone.sh with the executable bit set.

set -eu

# Xcode Cloud sets CI_PRIMARY_REPOSITORY_PATH to the primary checkout root.
# Fall back to walking up from this script (ci_scripts -> ios -> mobile -> root).
REPO="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/../../.." && pwd)}"

echo "--- Installing build tools (xcodegen + JDK) ---"
# Homebrew is preinstalled on Xcode Cloud. The Gradle wrapper (pinned 9.6.1)
# is committed, so only xcodegen and a JVM to launch it are needed here.
brew install xcodegen openjdk

# Homebrew's openjdk is keg-only; point Gradle at it explicitly.
JAVA_HOME="$(brew --prefix openjdk)/libexec/openjdk.jdk/Contents/Home"
export JAVA_HOME
export PATH="$JAVA_HOME/bin:$PATH"

echo "--- Building the KMP core XCFramework ---"
# Debug slice: matches the framework path project.yml links. First run also
# downloads the Kotlin/Native toolchain and builds libsodium from source, so
# this step is the slow one.
cd "$REPO/mobile/core"
./gradlew --no-daemon assembleTraumabomenCoreDebugXCFramework

echo "--- Generating the Xcode project from project.yml ---"
cd "$REPO/mobile/ios"
xcodegen generate

echo "--- ci_post_clone complete ---"
