#!/bin/sh
# Xcode Cloud custom build script. Runs after the repo is cloned and before
# dependency resolution / the archive build.
#
# A fresh clone has neither the Xcode project nor the core framework:
#   - mobile/ios/Traumatrees.xcodeproj is generated by xcodegen and gitignored.
#   - The KMP core is consumed as a Gradle-built XCFramework under
#     mobile/core/build/ (a build output, also not committed).
# This script rebuilds both so the subsequent archive finds a real project
# that links a real framework. Without it Xcode Cloud fails with
# "Project Traumatrees.xcodeproj does not exist".
#
# Location matters: Xcode Cloud only runs this when the folder is named exactly
# ci_scripts and sits next to the Xcode project it builds (mobile/ios), and the
# file is named ci_post_clone.sh with the executable bit set.

set -eu

# Xcode Cloud sets CI_PRIMARY_REPOSITORY_PATH to the primary checkout root.
# Fall back to walking up from this script (ci_scripts -> ios -> mobile -> root).
REPO="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/../../.." && pwd)}"

# Retry a network-heavy command a few times. A cold Xcode Cloud build downloads
# Homebrew bottles, the Kotlin/Native toolchain (~1GB), libsodium source, and
# Gradle dependencies; any can hiccup transiently and fail the whole script, so
# a transient failure self-recovers instead of failing the build.
retry() {
    attempt=1
    max=3
    until "$@"; do
        status=$?
        if [ "$attempt" -ge "$max" ]; then
            echo "retry: '$*' failed after $max attempts (exit $status)"
            return "$status"
        fi
        echo "retry: '$*' failed (exit $status); attempt $attempt/$max, retrying in 15s"
        attempt=$((attempt + 1))
        sleep 15
    done
}

echo "--- Installing build tools (xcodegen + JDK) ---"
# Homebrew is preinstalled on Xcode Cloud and verifies each formula's bottle
# checksum on download. Supply-chain posture of everything this script pulls:
#   - Gradle distribution: SHA-256 pinned in gradle/wrapper/gradle-wrapper.properties
#   - libsodium: version + SHA-256 pinned in mobile/core/scripts/build-libsodium.sh
#   - JDK: pinned to a fixed LTS major (openjdk@21) to avoid version drift
#   - Kotlin/Native + Maven deps: resolved by the pinned Gradle build
# xcodegen only rewrites our own project.yml into a project, so it tracks the
# current formula.
retry brew install xcodegen openjdk@21

# Homebrew's openjdk is keg-only; point Gradle at it explicitly.
JAVA_HOME="$(brew --prefix openjdk@21)/libexec/openjdk.jdk/Contents/Home"
export JAVA_HOME
export PATH="$JAVA_HOME/bin:$PATH"

echo "--- Building the KMP core XCFramework ---"
# Debug slice: matches the framework path project.yml links. First run also
# downloads the Kotlin/Native toolchain and builds libsodium from source, so
# this step is the slow one.
cd "$REPO/mobile/core"
retry ./gradlew --no-daemon assembleTraumabomenCoreDebugXCFramework

echo "--- Generating the Xcode project from project.yml ---"
cd "$REPO/mobile/ios"
xcodegen generate

# Stamp versions so every TestFlight build is unique and matches the release
# tag, without hand-editing project.yml. The workflow triggers on v* tags
# (make bump), so:
#   - CFBundleVersion            = CI_BUILD_NUMBER (Xcode Cloud's monotonic counter)
#   - CFBundleShortVersionString = the v* tag, minus the leading "v"
# Both fall back to the project.yml literals when either variable is absent
# (e.g. a manually started build).
PLIST="$REPO/mobile/ios/Info.plist"
if [ -n "${CI_BUILD_NUMBER:-}" ]; then
    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $CI_BUILD_NUMBER" "$PLIST"
    echo "CFBundleVersion -> $CI_BUILD_NUMBER"
fi
if [ -n "${CI_TAG:-}" ]; then
    MARKETING="${CI_TAG#v}"
    /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $MARKETING" "$PLIST"
    echo "CFBundleShortVersionString -> $MARKETING"
fi

echo "--- ci_post_clone complete ---"
