package org.traumabomen.core.crypto

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * The shared cross-platform compatibility suite, asserting the same golden
 * fixture as frontend/src/lib/cryptoCompat.unit.test.ts. The fixture was
 * generated by the real web stack (argon2-browser WASM + WebCrypto), so a
 * pass here means this implementation interoperates with every existing
 * user's data.
 */
class CryptoCompatTest {
    private val fx: JsonObject =
        Json.parseToJsonElement(File(System.getProperty("cryptoFixture")).readText()).jsonObject

    private fun s(key: String): String = fx[key]!!.jsonPrimitive.content

    private fun masterKey(): AesGcmKey = TraumaCrypto.deriveMasterKey(s("passphrase"), s("salt"))

    @OptIn(ExperimentalStdlibApi::class)
    @Test
    fun argon2idMatchesTheWebDerivation() {
        val derived = argon2idDeriveKey(s("passphrase"), kotlin.io.encoding.Base64.decode(s("salt")))
        assertEquals(s("masterKeyHex"), derived.toHexString())
    }

    @Test
    fun keyRingDecryptsToTheExpectedTreeKey() {
        val keyRing = TraumaCrypto.decryptKeyRing(s("encryptedKeyRing"), masterKey())
        assertEquals(mapOf(s("treeId") to s("treeKeyB64")), keyRing)
    }

    @Test
    fun personBlobDecryptsThroughTheUnwrappedTreeKey() {
        val keyRing = TraumaCrypto.decryptKeyRing(s("encryptedKeyRing"), masterKey())
        val treeKey = TraumaCrypto.importTreeKey(keyRing.getValue(s("treeId")))
        val person: JsonObject = TraumaCrypto.decryptFromApi(s("encryptedPerson"), treeKey)
        assertEquals(fx["personPlaintext"]!!.jsonObject, person)
    }

    @Test
    fun journalBlobDecrypts() {
        val treeKey = TraumaCrypto.importTreeKey(s("treeKeyB64"))
        val journal: JsonObject = TraumaCrypto.decryptFromApi(s("encryptedJournal"), treeKey)
        assertEquals(fx["journalPlaintext"]!!.jsonObject, journal)
    }

    @Test
    fun encryptForApiRoundTripsInTheWebFormat() {
        val treeKey = TraumaCrypto.importTreeKey(s("treeKeyB64"))
        val payload = mapOf("content" to "vanaf de telefoon, met ësc@pes")
        val encrypted = TraumaCrypto.encryptForApi(payload, treeKey)

        val blob = Json.decodeFromString<EncryptedBlob>(encrypted)
        assertEquals(IV_LENGTH, kotlin.io.encoding.Base64.decode(blob.iv).size)

        val decrypted: Map<String, String> = TraumaCrypto.decryptFromApi(encrypted, treeKey)
        assertEquals(payload, decrypted)
    }

    @Test
    fun everyEncryptUsesAFreshIv() {
        val treeKey = TraumaCrypto.importTreeKey(s("treeKeyB64"))
        val ivs = (1..50).map { Json.decodeFromString<EncryptedBlob>(TraumaCrypto.encryptForApi("x", treeKey)).iv }
        assertEquals(ivs.size, ivs.toSet().size, "IVs must never repeat")
    }

    @Test
    fun wrongKeyFailsAuthentication() {
        val wrongKey = AesGcmKey(ByteArray(32) { it.toByte() })
        assertFailsWith<DecryptException> {
            TraumaCrypto.decryptFromApi<JsonObject>(s("encryptedPerson"), wrongKey)
        }
    }

    @Test
    fun derivationIsDeterministic() {
        val a = argon2idDeriveKey(s("passphrase"), kotlin.io.encoding.Base64.decode(s("salt")))
        val b = argon2idDeriveKey(s("passphrase"), kotlin.io.encoding.Base64.decode(s("salt")))
        assertTrue(a.contentEquals(b))
        val other = argon2idDeriveKey(s("passphrase") + "x", kotlin.io.encoding.Base64.decode(s("salt")))
        assertNotEquals(a.toList(), other.toList())
    }
}
