"""Spike: prove libsodium reproduces the web client's crypto byte-for-byte.

Verifies, against fixture.json (generated by the real web stack:
argon2-browser WASM + WebCrypto in Chromium):

1. Argon2id via libsodium crypto_pwhash (the exact primitive the KMP core
   will bind on iOS and Android) derives the same master key.
2. AES-256-GCM decrypts the key ring, unwraps the tree key, and decrypts
   person and journal blobs to the expected plaintexts.
3. A round-trip in the other direction: encrypt fresh plaintext here in the
   web blob format, then decrypt it with an independent implementation
   (checked again by the browser in the spike run log).

Run: /tmp/spike-venv/bin/python verify_libsodium.py
"""

import base64
import hashlib
import json
import os
import sys

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from nacl import bindings

HERE = os.path.dirname(os.path.abspath(__file__))
# Canonical fixture location (shared with the frontend Vitest guard and the
# future KMP compatibility suite).
FIXTURE = os.path.join(HERE, "../../../frontend/src/fixtures/crypto-compat.fixture.json")


def decrypt_blob(encrypted: str, key: bytes) -> str:
    """Decrypt one web-format blob: JSON {iv, ciphertext}, both base64,
    ciphertext carrying the GCM tag appended (WebCrypto layout)."""
    blob = json.loads(encrypted)
    iv = base64.b64decode(blob["iv"])
    ct_and_tag = base64.b64decode(blob["ciphertext"])
    assert len(iv) == 12, f"IV must be 12 bytes, got {len(iv)}"
    return AESGCM(key).decrypt(iv, ct_and_tag, None).decode("utf-8")


def encrypt_blob(plaintext: str, key: bytes) -> str:
    """Encrypt in the exact web blob format (fresh random 12-byte IV)."""
    iv = os.urandom(12)
    ct_and_tag = AESGCM(key).encrypt(iv, plaintext.encode("utf-8"), None)
    return json.dumps(
        {
            "iv": base64.b64encode(iv).decode(),
            "ciphertext": base64.b64encode(ct_and_tag).decode(),
        }
    )


def main() -> int:
    with open(FIXTURE, "rb") as f:
        fx = json.load(f)

    failures = []

    def check(name: str, ok: bool, detail: str = "") -> None:
        print(f"  {'PASS' if ok else 'FAIL'}  {name}" + (f"  ({detail})" if detail else ""))
        if not ok:
            failures.append(name)

    print("1. Argon2id key derivation (libsodium crypto_pwhash)")
    master = bindings.crypto_pwhash_alg(
        outlen=fx["argon2"]["hashLen"],
        passwd=fx["passphrase"].encode("utf-8"),
        salt=base64.b64decode(fx["salt"]),
        opslimit=fx["argon2"]["time"],
        memlimit=fx["argon2"]["memKiB"] * 1024,
        alg=bindings.crypto_pwhash_ALG_ARGON2ID13,
    )
    check(
        "master key matches web derivation",
        master.hex() == fx["masterKeyHex"],
        f"libsodium={master.hex()[:16]}... web={fx['masterKeyHex'][:16]}...",
    )

    print("2. Key ring decryption (AES-256-GCM, master key)")
    key_ring = json.loads(decrypt_blob(fx["encryptedKeyRing"], master))
    check("key ring plaintext matches", key_ring == fx["keyRingPlaintext"])

    tree_key = base64.b64decode(key_ring[fx["treeId"]])
    check("tree key unwraps to expected bytes", base64.b64encode(tree_key).decode() == fx["treeKeyB64"])

    print("3. Entity decryption (AES-256-GCM, tree key)")
    person = json.loads(decrypt_blob(fx["encryptedPerson"], tree_key))
    check("person plaintext matches", person == fx["personPlaintext"])
    journal = json.loads(decrypt_blob(fx["encryptedJournal"], tree_key))
    check("journal plaintext matches", journal == fx["journalPlaintext"])

    print("4. Passphrase hash (SHA-256)")
    ph = base64.b64encode(hashlib.sha256(fx["passphrase"].encode("utf-8")).digest()).decode()
    check("passphrase hash matches", ph == fx["passphraseHashB64"])

    print("5. Reverse direction: encrypt here, decrypt independently")
    reverse = encrypt_blob(json.dumps({"content": "geschreven op de telefoon"}), tree_key)
    roundtrip = json.loads(decrypt_blob(reverse, tree_key))
    check("native-encrypted blob round-trips", roundtrip == {"content": "geschreven op de telefoon"})
    with open(os.path.join(HERE, "native-encrypted.json"), "w") as f:
        f.write(reverse)
    print("     wrote native-encrypted.json for browser-side verification")

    print()
    if failures:
        print(f"SPIKE FAILED: {len(failures)} check(s): {', '.join(failures)}")
        return 1
    print("SPIKE PASSED: libsodium + AES-GCM reproduce the web format byte-for-byte.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
