import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { decryptFromApi, decryptKeyRing, hashPassphrase, importTreeKey } from "./crypto";

/**
 * Cross-platform crypto compatibility guard.
 *
 * src/fixtures/crypto-compat.fixture.json was generated by the real web
 * stack (argon2-browser WASM + WebCrypto in Chromium) and is also asserted
 * by the mobile KMP core's test suite: if either side drifts from the shared
 * blob format, one of the two CI suites breaks.
 *
 * The Argon2id derivation itself cannot run under Vitest (the WASM bundle is
 * a browser global), so the fixture pins the derived master key and this
 * suite verifies everything downstream of it through the real crypto.ts
 * functions. The derivation equivalence is proven in
 * mobile/spikes/crypto-compat/ and re-proven by the KMP suite.
 */

const fixture = JSON.parse(
  readFileSync(resolve(process.cwd(), "src/fixtures/crypto-compat.fixture.json"), "utf8"),
);

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

async function importMasterKey(): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    "raw",
    hexToBytes(fixture.masterKeyHex).buffer as ArrayBuffer,
    { name: "AES-GCM" },
    false,
    ["encrypt", "decrypt"],
  );
}

describe("crypto compatibility fixture", () => {
  it("decrypts the key ring with the fixture master key", async () => {
    const masterKey = await importMasterKey();
    const keyRing = await decryptKeyRing(fixture.encryptedKeyRing, masterKey);
    expect(keyRing).toEqual(fixture.keyRingPlaintext);
  });

  it("unwraps the tree key and decrypts the person blob", async () => {
    const masterKey = await importMasterKey();
    const keyRing = await decryptKeyRing(fixture.encryptedKeyRing, masterKey);
    const treeKey = await importTreeKey(keyRing[fixture.treeId]);
    const person = await decryptFromApi(fixture.encryptedPerson, treeKey);
    expect(person).toEqual(fixture.personPlaintext);
  });

  it("decrypts the journal blob", async () => {
    const treeKey = await importTreeKey(fixture.treeKeyB64);
    const journal = await decryptFromApi(fixture.encryptedJournal, treeKey);
    expect(journal).toEqual(fixture.journalPlaintext);
  });

  it("reproduces the passphrase hash", async () => {
    expect(await hashPassphrase(fixture.passphrase)).toBe(fixture.passphraseHashB64);
  });

  it("pins the agreed Argon2id parameters", () => {
    expect(fixture.argon2).toEqual({
      time: 3,
      memKiB: 65536,
      hashLen: 32,
      parallelism: 1,
      type: "argon2id",
    });
  });
});
